### ISSUE TITLE
Add a Transient Manager

### ISSUE THREAD

**Issue by lusimeon** [studiometa/create-wordpress-project#45]
Hello, I think we need a transient manager.
- Creation (based on `Timber::transient`?)
- Deletion (based on YAML config)

I'll push a PR soon about this one.

**Comment by titouanmathis** [comment]
How would this manager be used? Do you have any examples? Could you share some details on its usage and implementation?

**Comment by lusimeon** [comment]
# Summary

Wrapper of native transient functions + additionnal feature who clean transient on post/term/options update. 

# Basic example

In my opinion, the creation and the deletion method need to just be a wrapper of Wordpress or Timber native function.
But the manager will add an automatic transient "cleaner" based on a YAML config. Below an example:
```yml
# Clean one content of all type updated (post / term / options)
all:
    - transient_all
# Clean on post update
post:
    - transient_bar
    - transient_foo
# Clean on custom post update
custom_post_type_key:
    - transient_baz
    - transient_foo_bar
# Clean on category taxonomy update
category:
    - name_of_by_transient_category
```

With example on top, when we save a post, the manager will delete transients who start with values defined (`transient_bar` and `transient_foo`). So a transient called `transient_foo`, `transient_foo_baz` or `transient_foobar` will be deleted.

# Motivation

Rather than (or in addition to) set a lifetime to a transient, we often need to clean a transient when a post is saved to update the front-office. So this PR will introduce a way to clean transients based on a YAML config.
